#include <TLorentzVector.h>
#include <TVector3.h>
#include <TTree.h>
#include <TCanvas.h>
#include <TProfile.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TFile.h>
#include <TLegend.h>
#include <TStyle.h>
#include <TFormula.h>
#include <TF1.h>
#include <TSystem.h>
#include <TClonesArray.h>
#include <TLeaf.h>
#include <TChain.h>
#include <TObject.h>
#include <string.h>
#include <algorithm>
#include <TBranch.h>
#include <TString.h>
#include <TBits.h>
#include <TMath.h>
#include "TROOT.h"
#include <iostream>
#include <iomanip>
#include <sstream>
#include <TLatex.h>

#include "DrawDataMC.h"

#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootBardak.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootBeamSpot.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootCluster.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootEcalRecHit.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootElectron.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootEvent.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootJet.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootMCParticle.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootMCPhoton.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootMET.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootMuon.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootParticle.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootPhoton.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootRun.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootSignalEvent.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootSuperCluster.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootTopTop.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootTrack.h"
#include "/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/interface/TRootVertex.h"



#pragma optimize 0

using namespace std;
	
//int plotDataMC_TDR_miniTree()
int main()
{
	string selection = "noMuIso-hadEt-noDeltaRmin";
	gSystem->Load("/sps/cms/obondu/CMSSW_3_6_1_patch4/src/UserCode/IpnTreeProducer/src/libToto.so");
	gROOT->ProcessLine(".x setTDRStyle.C");
	string Data = "Selected/" + selection + "/miniTree_DATA_ALL.root"; 
	string PhotonJet_Pt15 = "Selected/" + selection + "/PhotonJet_Pt15/miniTree_PhotonJet_Pt15_ALL.root"; 
	string PhotonJet_Pt30 = "Selected/" + selection + "/PhotonJet_Pt30/miniTree_PhotonJet_Pt30_ALL.root"; 
	string PhotonJet_Pt80 = "Selected/" + selection + "/PhotonJet_Pt80/miniTree_PhotonJet_Pt80_ALL.root"; 
	string PhotonJet_Pt170 = "Selected/" + selection + "/PhotonJet_Pt170/miniTree_PhotonJet_Pt170_ALL.root"; 
	string PhotonJet_Pt300 = "Selected/" + selection + "/PhotonJet_Pt300/miniTree_PhotonJet_Pt300_ALL.root"; 
	string QCD_Pt15 = "Selected/" + selection + "/QCD_Pt15/miniTree_QCD_Pt15_ALL.root"; 
	string QCD_Pt30 = "Selected/" + selection + "/QCD_Pt30/miniTree_QCD_Pt30_ALL.root"; 
	string QCD_Pt80 = "Selected/" + selection + "/QCD_Pt80/miniTree_QCD_Pt80_ALL.root"; 
	string QCD_Pt170 = "Selected/" + selection + "/QCD_Pt170/miniTree_QCD_Pt170_ALL.root"; 
	string QCD_Pt300 = "Selected/" + selection + "/QCD_Pt300/miniTree_QCD_Pt300_ALL.root"; 
	string QCD_Pt470 = "Selected/" + selection + "/QCD_Pt470/miniTree_QCD_Pt470_ALL.root"; 
	string TTbarJets_Tauola = "Selected/" + selection + "/TTbarJets_Tauola-madgraph/miniTree_TTbarJets_Tauola-madgraph_ALL.root";
	string WJets_7TeV = "Selected/" + selection + "/WJets_7TeV-madgraph-tauola/miniTree_WJets_7TeV-madgraph-tauola_ALL.root";
	string ZJets_7TeV = "Selected/" + selection + "/ZJets_7TeV-madgraph-tauola/miniTree_ZJets_7TeV-madgraph-tauola_ALL.root";
	string QCD_Mu_Pt20to30 = "Selected/" + selection + "/QCD_Mu_Pt20to30/miniTree_QCD_Mu_Pt20to30_ALL.root";
	string QCD_Mu_Pt30to50 = "Selected/" + selection + "/QCD_Mu_Pt30to50/miniTree_QCD_Mu_Pt30to50_ALL.root";
	string QCD_Mu_Pt50to80 = "Selected/" + selection + "/QCD_Mu_Pt50to80/miniTree_QCD_Mu_Pt50to80_ALL.root";
	string QCD_Mu_Pt80to120 = "Selected/" + selection + "/QCD_Mu_Pt80to120/miniTree_QCD_Mu_Pt80to120_ALL.root";
	string QCD_Mu_Pt120to170 = "Selected/" + selection + "/QCD_Mu_Pt120to170/miniTree_QCD_Mu_Pt120to170_ALL.root";
	string QCD_Mu_Pt170toInf = "Selected/" + selection + "/QCD_Mu_Pt170toInf/miniTree_QCD_Mu_Pt170toInf_ALL.root";
	string InclusiveMu15 = "Selected/" + selection + "/InclusiveMu15/miniTree_InclusiveMu15_ALL.root"; 
	string FSR_ZmumuJet_Pt0to15 = "Selected/" + selection + "/FSR_ZmumuJet_Pt0to15/miniTree_FSR_ZmumuJet_Pt0to15_ALL.root";
	string FSR_ZmumuJet_Pt15to20 = "Selected/" + selection + "/FSR_ZmumuJet_Pt15to20/miniTree_FSR_ZmumuJet_Pt15to20_ALL.root";
	string FSR_ZmumuJet_Pt20to30 = "Selected/" + selection + "/FSR_ZmumuJet_Pt20to30/miniTree_FSR_ZmumuJet_Pt20to30_ALL.root";
	string FSR_ZmumuJet_Pt30to50 = "Selected/" + selection + "/FSR_ZmumuJet_Pt30to50/miniTree_FSR_ZmumuJet_Pt30to50_ALL.root";
	string FSR_ZmumuJet_Pt50to80 = "Selected/" + selection + "/FSR_ZmumuJet_Pt50to80/miniTree_FSR_ZmumuJet_Pt50to80_ALL.root";
	string FSR_ZmumuJet_Pt80to120 = "Selected/" + selection + "/FSR_ZmumuJet_Pt80to120/miniTree_FSR_ZmumuJet_Pt80to120_ALL.root";
	string FSR_ZmumuJet_Pt120to170 = "Selected/" + selection + "/FSR_ZmumuJet_Pt120to170/miniTree_FSR_ZmumuJet_Pt120to170_ALL.root";
	string FSR_ZmumuJet_Pt170to230 = "Selected/" + selection + "/FSR_ZmumuJet_Pt170to230/miniTree_FSR_ZmumuJet_Pt170to230_ALL.root";
	string FSR_ZmumuJet_Pt230to300 = "Selected/" + selection + "/FSR_ZmumuJet_Pt230to300/miniTree_FSR_ZmumuJet_Pt230to300_ALL.root";
	string FSR_ZmumuJet_Pt300toInf = "Selected/" + selection + "/FSR_ZmumuJet_Pt300toInf/miniTree_FSR_ZmumuJet_Pt300toInf_ALL.root";
	string ISR_ZmumuJet_Pt0to15 = "Selected/" + selection + "/ISR_ZmumuJet_Pt0to15/miniTree_ISR_ZmumuJet_Pt0to15_ALL.root";
	string ISR_ZmumuJet_Pt15to20 = "Selected/" + selection + "/ISR_ZmumuJet_Pt15to20/miniTree_ISR_ZmumuJet_Pt15to20_ALL.root";
	string ISR_ZmumuJet_Pt20to30 = "Selected/" + selection + "/ISR_ZmumuJet_Pt20to30/miniTree_ISR_ZmumuJet_Pt20to30_ALL.root";
	string ISR_ZmumuJet_Pt30to50 = "Selected/" + selection + "/ISR_ZmumuJet_Pt30to50/miniTree_ISR_ZmumuJet_Pt30to50_ALL.root";
	string ISR_ZmumuJet_Pt50to80 = "Selected/" + selection + "/ISR_ZmumuJet_Pt50to80/miniTree_ISR_ZmumuJet_Pt50to80_ALL.root";
	string ISR_ZmumuJet_Pt80to120 = "Selected/" + selection + "/ISR_ZmumuJet_Pt80to120/miniTree_ISR_ZmumuJet_Pt80to120_ALL.root";
	string ISR_ZmumuJet_Pt120to170 = "Selected/" + selection + "/ISR_ZmumuJet_Pt120to170/miniTree_ISR_ZmumuJet_Pt120to170_ALL.root";
	string ISR_ZmumuJet_Pt170to230 = "Selected/" + selection + "/ISR_ZmumuJet_Pt170to230/miniTree_ISR_ZmumuJet_Pt170to230_ALL.root";
	string ISR_ZmumuJet_Pt230to300 = "Selected/" + selection + "/ISR_ZmumuJet_Pt230to300/miniTree_ISR_ZmumuJet_Pt230to300_ALL.root";
	string ISR_ZmumuJet_Pt300toInf = "Selected/" + selection + "/ISR_ZmumuJet_Pt300toInf/miniTree_ISR_ZmumuJet_Pt300toInf_ALL.root";
	
	TFile *Data_File = new TFile(Data.c_str());
	TTree* Data_miniTree = (TTree*) Data_File->Get("miniTree");
	TTree* Data_miniTree_allmuons = (TTree*) Data_File->Get("miniTree_allmuons");
	TTree* Data_miniTree_allphotons = (TTree*) Data_File->Get("miniTree_allphotons");
	TFile *PhotonJet_Pt15_File = new TFile(PhotonJet_Pt15.c_str());
	TTree* PhotonJet_Pt15_miniTree = (TTree*) PhotonJet_Pt15_File->Get("miniTree");
	TTree* PhotonJet_Pt15_miniTree_allmuons = (TTree*) PhotonJet_Pt15_File->Get("miniTree_allmuons");
	TTree* PhotonJet_Pt15_miniTree_allphotons = (TTree*) PhotonJet_Pt15_File->Get("miniTree_allphotons");
	TFile *PhotonJet_Pt30_File = new TFile(PhotonJet_Pt30.c_str());
	TTree* PhotonJet_Pt30_miniTree = (TTree*) PhotonJet_Pt30_File->Get("miniTree");
	TTree* PhotonJet_Pt30_miniTree_allmuons = (TTree*) PhotonJet_Pt30_File->Get("miniTree_allmuons");
	TTree* PhotonJet_Pt30_miniTree_allphotons = (TTree*) PhotonJet_Pt30_File->Get("miniTree_allphotons");
	TFile *PhotonJet_Pt80_File = new TFile(PhotonJet_Pt80.c_str());
	TTree* PhotonJet_Pt80_miniTree = (TTree*) PhotonJet_Pt80_File->Get("miniTree");
	TTree* PhotonJet_Pt80_miniTree_allmuons = (TTree*) PhotonJet_Pt80_File->Get("miniTree_allmuons");
	TTree* PhotonJet_Pt80_miniTree_allphotons = (TTree*) PhotonJet_Pt80_File->Get("miniTree_allphotons");
	TFile *PhotonJet_Pt170_File = new TFile(PhotonJet_Pt170.c_str());
	TTree* PhotonJet_Pt170_miniTree = (TTree*) PhotonJet_Pt170_File->Get("miniTree");
	TTree* PhotonJet_Pt170_miniTree_allmuons = (TTree*) PhotonJet_Pt170_File->Get("miniTree_allmuons");
	TTree* PhotonJet_Pt170_miniTree_allphotons = (TTree*) PhotonJet_Pt170_File->Get("miniTree_allphotons");
	TFile *PhotonJet_Pt300_File = new TFile(PhotonJet_Pt300.c_str());
	TTree* PhotonJet_Pt300_miniTree = (TTree*) PhotonJet_Pt300_File->Get("miniTree");
	TTree* PhotonJet_Pt300_miniTree_allmuons = (TTree*) PhotonJet_Pt300_File->Get("miniTree_allmuons");
	TTree* PhotonJet_Pt300_miniTree_allphotons = (TTree*) PhotonJet_Pt300_File->Get("miniTree_allphotons");
	TFile *QCD_Pt15_File = new TFile(QCD_Pt15.c_str());
	TTree* QCD_Pt15_miniTree = (TTree*) QCD_Pt15_File->Get("miniTree");
	TTree* QCD_Pt15_miniTree_allmuons = (TTree*) QCD_Pt15_File->Get("miniTree_allmuons");
	TTree* QCD_Pt15_miniTree_allphotons = (TTree*) QCD_Pt15_File->Get("miniTree_allphotons");
	TFile *QCD_Pt30_File = new TFile(QCD_Pt30.c_str());
	TTree* QCD_Pt30_miniTree = (TTree*) QCD_Pt30_File->Get("miniTree");
	TTree* QCD_Pt30_miniTree_allmuons = (TTree*) QCD_Pt30_File->Get("miniTree_allmuons");
	TTree* QCD_Pt30_miniTree_allphotons = (TTree*) QCD_Pt30_File->Get("miniTree_allphotons");
	TFile *QCD_Pt80_File = new TFile(QCD_Pt80.c_str());
	TTree* QCD_Pt80_miniTree = (TTree*) QCD_Pt80_File->Get("miniTree");
	TTree* QCD_Pt80_miniTree_allmuons = (TTree*) QCD_Pt80_File->Get("miniTree_allmuons");
	TTree* QCD_Pt80_miniTree_allphotons = (TTree*) QCD_Pt80_File->Get("miniTree_allphotons");
	TFile *QCD_Pt170_File = new TFile(QCD_Pt170.c_str());
	TTree* QCD_Pt170_miniTree = (TTree*) QCD_Pt170_File->Get("miniTree");
	TTree* QCD_Pt170_miniTree_allmuons = (TTree*) QCD_Pt170_File->Get("miniTree_allmuons");
	TTree* QCD_Pt170_miniTree_allphotons = (TTree*) QCD_Pt170_File->Get("miniTree_allphotons");
	TFile *QCD_Pt300_File = new TFile(QCD_Pt300.c_str());
	TTree* QCD_Pt300_miniTree = (TTree*) QCD_Pt300_File->Get("miniTree");
	TTree* QCD_Pt300_miniTree_allmuons = (TTree*) QCD_Pt300_File->Get("miniTree_allmuons");
	TTree* QCD_Pt300_miniTree_allphotons = (TTree*) QCD_Pt300_File->Get("miniTree_allphotons");
	TFile *QCD_Pt470_File = new TFile(QCD_Pt470.c_str());
	TTree* QCD_Pt470_miniTree = (TTree*) QCD_Pt470_File->Get("miniTree");
	TTree* QCD_Pt470_miniTree_allmuons = (TTree*) QCD_Pt470_File->Get("miniTree_allmuons");
	TTree* QCD_Pt470_miniTree_allphotons = (TTree*) QCD_Pt470_File->Get("miniTree_allphotons");
	TFile *TTbarJets_Tauola_File = new TFile(TTbarJets_Tauola.c_str());
	TTree* TTbarJets_Tauola_miniTree = (TTree*) TTbarJets_Tauola_File->Get("miniTree");
	TTree* TTbarJets_Tauola_miniTree_allmuons = (TTree*) TTbarJets_Tauola_File->Get("miniTree_allmuons");
	TTree* TTbarJets_Tauola_miniTree_allphotons = (TTree*) TTbarJets_Tauola_File->Get("miniTree_allphotons");
	TFile *WJets_7TeV_File = new TFile(WJets_7TeV.c_str());
	TTree* WJets_7TeV_miniTree = (TTree*) WJets_7TeV_File->Get("miniTree");
	TTree* WJets_7TeV_miniTree_allmuons = (TTree*) WJets_7TeV_File->Get("miniTree_allmuons");
	TTree* WJets_7TeV_miniTree_allphotons = (TTree*) WJets_7TeV_File->Get("miniTree_allphotons");
	TFile *ZJets_7TeV_File = new TFile(ZJets_7TeV.c_str());
	TTree* ZJets_7TeV_miniTree = (TTree*) ZJets_7TeV_File->Get("miniTree");
	TTree* ZJets_7TeV_miniTree_allmuons = (TTree*) ZJets_7TeV_File->Get("miniTree_allmuons");
	TTree* ZJets_7TeV_miniTree_allphotons = (TTree*) ZJets_7TeV_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt20to30_File = new TFile(QCD_Mu_Pt20to30.c_str());
	TTree* QCD_Mu_Pt20to30_miniTree = (TTree*) QCD_Mu_Pt20to30_File->Get("miniTree");
	TTree* QCD_Mu_Pt20to30_miniTree_allmuons = (TTree*) QCD_Mu_Pt20to30_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt20to30_miniTree_allphotons = (TTree*) QCD_Mu_Pt20to30_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt30to50_File = new TFile(QCD_Mu_Pt30to50.c_str());
	TTree* QCD_Mu_Pt30to50_miniTree = (TTree*) QCD_Mu_Pt30to50_File->Get("miniTree");
	TTree* QCD_Mu_Pt30to50_miniTree_allmuons = (TTree*) QCD_Mu_Pt30to50_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt30to50_miniTree_allphotons = (TTree*) QCD_Mu_Pt30to50_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt50to80_File = new TFile(QCD_Mu_Pt50to80.c_str());
	TTree* QCD_Mu_Pt50to80_miniTree = (TTree*) QCD_Mu_Pt50to80_File->Get("miniTree");
	TTree* QCD_Mu_Pt50to80_miniTree_allmuons = (TTree*) QCD_Mu_Pt50to80_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt50to80_miniTree_allphotons = (TTree*) QCD_Mu_Pt50to80_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt80to120_File = new TFile(QCD_Mu_Pt80to120.c_str());
	TTree* QCD_Mu_Pt80to120_miniTree = (TTree*) QCD_Mu_Pt80to120_File->Get("miniTree");
	TTree* QCD_Mu_Pt80to120_miniTree_allmuons = (TTree*) QCD_Mu_Pt80to120_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt80to120_miniTree_allphotons = (TTree*) QCD_Mu_Pt80to120_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt120to170_File = new TFile(QCD_Mu_Pt120to170.c_str());
	TTree* QCD_Mu_Pt120to170_miniTree = (TTree*) QCD_Mu_Pt120to170_File->Get("miniTree");
	TTree* QCD_Mu_Pt120to170_miniTree_allmuons = (TTree*) QCD_Mu_Pt120to170_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt120to170_miniTree_allphotons = (TTree*) QCD_Mu_Pt120to170_File->Get("miniTree_allphotons");
	TFile *QCD_Mu_Pt170toInf_File = new TFile(QCD_Mu_Pt170toInf.c_str());
	TTree* QCD_Mu_Pt170toInf_miniTree = (TTree*) QCD_Mu_Pt170toInf_File->Get("miniTree");
	TTree* QCD_Mu_Pt170toInf_miniTree_allmuons = (TTree*) QCD_Mu_Pt170toInf_File->Get("miniTree_allmuons");
	TTree* QCD_Mu_Pt170toInf_miniTree_allphotons = (TTree*) QCD_Mu_Pt170toInf_File->Get("miniTree_allphotons");
	TFile *InclusiveMu15_File = new TFile(InclusiveMu15.c_str());
	TTree* InclusiveMu15_miniTree = (TTree*) InclusiveMu15_File->Get("miniTree");
	TTree* InclusiveMu15_miniTree_allmuons = (TTree*) InclusiveMu15_File->Get("miniTree_allmuons");
	TTree* InclusiveMu15_miniTree_allphotons = (TTree*) InclusiveMu15_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt0to15_File = new TFile(FSR_ZmumuJet_Pt0to15.c_str());
	TTree* FSR_ZmumuJet_Pt0to15_miniTree = (TTree*) FSR_ZmumuJet_Pt0to15_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt0to15_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt0to15_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt0to15_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt0to15_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt15to20_File = new TFile(FSR_ZmumuJet_Pt15to20.c_str());
	TTree* FSR_ZmumuJet_Pt15to20_miniTree = (TTree*) FSR_ZmumuJet_Pt15to20_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt15to20_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt15to20_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt15to20_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt15to20_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt20to30_File = new TFile(FSR_ZmumuJet_Pt20to30.c_str());
	TTree* FSR_ZmumuJet_Pt20to30_miniTree = (TTree*) FSR_ZmumuJet_Pt20to30_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt20to30_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt20to30_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt20to30_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt20to30_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt30to50_File = new TFile(FSR_ZmumuJet_Pt30to50.c_str());
	TTree* FSR_ZmumuJet_Pt30to50_miniTree = (TTree*) FSR_ZmumuJet_Pt30to50_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt30to50_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt30to50_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt30to50_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt30to50_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt50to80_File = new TFile(FSR_ZmumuJet_Pt50to80.c_str());
	TTree* FSR_ZmumuJet_Pt50to80_miniTree = (TTree*) FSR_ZmumuJet_Pt50to80_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt50to80_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt50to80_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt50to80_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt50to80_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt80to120_File = new TFile(FSR_ZmumuJet_Pt80to120.c_str());
	TTree* FSR_ZmumuJet_Pt80to120_miniTree = (TTree*) FSR_ZmumuJet_Pt80to120_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt80to120_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt80to120_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt80to120_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt80to120_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt120to170_File = new TFile(FSR_ZmumuJet_Pt120to170.c_str());
	TTree* FSR_ZmumuJet_Pt120to170_miniTree = (TTree*) FSR_ZmumuJet_Pt120to170_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt120to170_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt120to170_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt120to170_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt120to170_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt170to230_File = new TFile(FSR_ZmumuJet_Pt170to230.c_str());
	TTree* FSR_ZmumuJet_Pt170to230_miniTree = (TTree*) FSR_ZmumuJet_Pt170to230_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt170to230_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt170to230_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt170to230_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt170to230_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt230to300_File = new TFile(FSR_ZmumuJet_Pt230to300.c_str());
	TTree* FSR_ZmumuJet_Pt230to300_miniTree = (TTree*) FSR_ZmumuJet_Pt230to300_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt230to300_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt230to300_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt230to300_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt230to300_File->Get("miniTree_allphotons");
	TFile *FSR_ZmumuJet_Pt300toInf_File = new TFile(FSR_ZmumuJet_Pt300toInf.c_str());
	TTree* FSR_ZmumuJet_Pt300toInf_miniTree = (TTree*) FSR_ZmumuJet_Pt300toInf_File->Get("miniTree");
	TTree* FSR_ZmumuJet_Pt300toInf_miniTree_allmuons = (TTree*) FSR_ZmumuJet_Pt300toInf_File->Get("miniTree_allmuons");
	TTree* FSR_ZmumuJet_Pt300toInf_miniTree_allphotons = (TTree*) FSR_ZmumuJet_Pt300toInf_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt0to15_File = new TFile(ISR_ZmumuJet_Pt0to15.c_str());
	TTree* ISR_ZmumuJet_Pt0to15_miniTree = (TTree*) ISR_ZmumuJet_Pt0to15_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt0to15_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt0to15_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt0to15_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt0to15_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt15to20_File = new TFile(ISR_ZmumuJet_Pt15to20.c_str());
	TTree* ISR_ZmumuJet_Pt15to20_miniTree = (TTree*) ISR_ZmumuJet_Pt15to20_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt15to20_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt15to20_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt15to20_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt15to20_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt20to30_File = new TFile(ISR_ZmumuJet_Pt20to30.c_str());
	TTree* ISR_ZmumuJet_Pt20to30_miniTree = (TTree*) ISR_ZmumuJet_Pt20to30_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt20to30_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt20to30_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt20to30_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt20to30_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt30to50_File = new TFile(ISR_ZmumuJet_Pt30to50.c_str());
	TTree* ISR_ZmumuJet_Pt30to50_miniTree = (TTree*) ISR_ZmumuJet_Pt30to50_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt30to50_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt30to50_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt30to50_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt30to50_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt50to80_File = new TFile(ISR_ZmumuJet_Pt50to80.c_str());
	TTree* ISR_ZmumuJet_Pt50to80_miniTree = (TTree*) ISR_ZmumuJet_Pt50to80_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt50to80_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt50to80_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt50to80_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt50to80_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt80to120_File = new TFile(ISR_ZmumuJet_Pt80to120.c_str());
	TTree* ISR_ZmumuJet_Pt80to120_miniTree = (TTree*) ISR_ZmumuJet_Pt80to120_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt80to120_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt80to120_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt80to120_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt80to120_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt120to170_File = new TFile(ISR_ZmumuJet_Pt120to170.c_str());
	TTree* ISR_ZmumuJet_Pt120to170_miniTree = (TTree*) ISR_ZmumuJet_Pt120to170_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt120to170_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt120to170_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt120to170_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt120to170_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt170to230_File = new TFile(ISR_ZmumuJet_Pt170to230.c_str());
	TTree* ISR_ZmumuJet_Pt170to230_miniTree = (TTree*) ISR_ZmumuJet_Pt170to230_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt170to230_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt170to230_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt170to230_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt170to230_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt230to300_File = new TFile(ISR_ZmumuJet_Pt230to300.c_str());
	TTree* ISR_ZmumuJet_Pt230to300_miniTree = (TTree*) ISR_ZmumuJet_Pt230to300_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt230to300_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt230to300_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt230to300_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt230to300_File->Get("miniTree_allphotons");
	TFile *ISR_ZmumuJet_Pt300toInf_File = new TFile(ISR_ZmumuJet_Pt300toInf.c_str());
	TTree* ISR_ZmumuJet_Pt300toInf_miniTree = (TTree*) ISR_ZmumuJet_Pt300toInf_File->Get("miniTree");
	TTree* ISR_ZmumuJet_Pt300toInf_miniTree_allmuons = (TTree*) ISR_ZmumuJet_Pt300toInf_File->Get("miniTree_allmuons");
	TTree* ISR_ZmumuJet_Pt300toInf_miniTree_allphotons = (TTree*) ISR_ZmumuJet_Pt300toInf_File->Get("miniTree_allphotons");


	TCanvas *c1 = new TCanvas("Default", "Default");

// NOTES:
// NO PHOTON/MUON INFORMATION IS FILLED IN BEFORE 2B
	vector<string> set_of_cuts;
	vector<string> name;
//	set_of_cuts.push_back("isBeforeAllCuts");
//	name.push_back("00Before");
//	set_of_cuts.push_back("isAfterCutPthatFilter");
//	name.push_back("0AfterCutPthatFilter");
//	set_of_cuts.push_back("isAfterCut1a");
//	name.push_back("After1a");
//	set_of_cuts.push_back("isAfterCut1b");
//	name.push_back("After1b");
//	set_of_cuts.push_back("isAfterCut1c");
//	name.push_back("After1c");
//	set_of_cuts.push_back("isAfterCut1d");
//	name.push_back("After1d");
//	set_of_cuts.push_back("isAfterCut1e");
//	name.push_back("After1e");
//	set_of_cuts.push_back("isAfterCut2a");
//	name.push_back("After2a");
//	set_of_cuts.push_back("isAfterCut2b");
//	name.push_back("After2b");
//	set_of_cuts.push_back("isAfterCut2c");
//	name.push_back("After2c");
//	set_of_cuts.push_back("isAfterCut3");
//  name.push_back("After3");
//	set_of_cuts.push_back("isAfterCut4");
//  name.push_back("After4");
//	set_of_cuts.push_back("isAfterCut5");
//  name.push_back("After5");
//	set_of_cuts.push_back("isAfterCut6");
//  name.push_back("After6");
//	set_of_cuts.push_back("isAfterCut7");
//  name.push_back("After7");
	set_of_cuts.push_back("isAfterCut8");
  name.push_back("After8");
//	set_of_cuts.push_back("isAfterCut8 && Mmumugamma < 95.2 && Mmumugamma > 87.2");
//	name.push_back("After8_tight_masswindow");	


	for(int i=0; i<set_of_cuts.size() ; i++){
/*

		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "NbMuons", "NbMuons", "(10,0,10)", set_of_cuts[i], name[i], "# of muons", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "NbPhotons", "NbPhotons", "(10,0,10)", set_of_cuts[i], name[i], "# of photons", true, false, c1);

		DrawDataMCplot(Data_miniTree_allmuons, QCD_Pt15_miniTree_allmuons, QCD_Pt30_miniTree_allmuons, QCD_Pt80_miniTree_allmuons, QCD_Pt170_miniTree_allmuons, QCD_Pt300_miniTree_allmuons, QCD_Pt470_miniTree_allmuons, PhotonJet_Pt15_miniTree_allmuons, PhotonJet_Pt30_miniTree_allmuons, PhotonJet_Pt80_miniTree_allmuons, PhotonJet_Pt170_miniTree_allmuons, PhotonJet_Pt300_miniTree_allmuons, TTbarJets_Tauola_miniTree_allmuons, WJets_7TeV_miniTree_allmuons, ZJets_7TeV_miniTree_allmuons, QCD_Mu_Pt20to30_miniTree_allmuons, QCD_Mu_Pt30to50_miniTree_allmuons, QCD_Mu_Pt50to80_miniTree_allmuons, QCD_Mu_Pt80to120_miniTree_allmuons, QCD_Mu_Pt120to170_miniTree_allmuons, QCD_Mu_Pt170toInf_miniTree_allmuons, InclusiveMu15_miniTree_allmuons, FSR_ZmumuJet_Pt0to15_miniTree_allmuons, FSR_ZmumuJet_Pt15to20_miniTree_allmuons, FSR_ZmumuJet_Pt20to30_miniTree_allmuons, FSR_ZmumuJet_Pt30to50_miniTree_allmuons, FSR_ZmumuJet_Pt50to80_miniTree_allmuons, FSR_ZmumuJet_Pt80to120_miniTree_allmuons, FSR_ZmumuJet_Pt120to170_miniTree_allmuons, FSR_ZmumuJet_Pt170to230_miniTree_allmuons, FSR_ZmumuJet_Pt230to300_miniTree_allmuons, FSR_ZmumuJet_Pt300toInf_miniTree_allmuons, ISR_ZmumuJet_Pt0to15_miniTree_allmuons, ISR_ZmumuJet_Pt15to20_miniTree_allmuons, ISR_ZmumuJet_Pt20to30_miniTree_allmuons, ISR_ZmumuJet_Pt30to50_miniTree_allmuons, ISR_ZmumuJet_Pt50to80_miniTree_allmuons, ISR_ZmumuJet_Pt80to120_miniTree_allmuons, ISR_ZmumuJet_Pt120to170_miniTree_allmuons, ISR_ZmumuJet_Pt170to230_miniTree_allmuons, ISR_ZmumuJet_Pt230to300_miniTree_allmuons, ISR_ZmumuJet_Pt300toInf_miniTree_allmuons, "Pt_allMuons", "Pt_allMuons", "(100,0,100)", set_of_cuts[i], name[i], "p_{T_{#mu}} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree_allmuons, QCD_Pt15_miniTree_allmuons, QCD_Pt30_miniTree_allmuons, QCD_Pt80_miniTree_allmuons, QCD_Pt170_miniTree_allmuons, QCD_Pt300_miniTree_allmuons, QCD_Pt470_miniTree_allmuons, PhotonJet_Pt15_miniTree_allmuons, PhotonJet_Pt30_miniTree_allmuons, PhotonJet_Pt80_miniTree_allmuons, PhotonJet_Pt170_miniTree_allmuons, PhotonJet_Pt300_miniTree_allmuons, TTbarJets_Tauola_miniTree_allmuons, WJets_7TeV_miniTree_allmuons, ZJets_7TeV_miniTree_allmuons, QCD_Mu_Pt20to30_miniTree_allmuons, QCD_Mu_Pt30to50_miniTree_allmuons, QCD_Mu_Pt50to80_miniTree_allmuons, QCD_Mu_Pt80to120_miniTree_allmuons, QCD_Mu_Pt120to170_miniTree_allmuons, QCD_Mu_Pt170toInf_miniTree_allmuons, InclusiveMu15_miniTree_allmuons, FSR_ZmumuJet_Pt0to15_miniTree_allmuons, FSR_ZmumuJet_Pt15to20_miniTree_allmuons, FSR_ZmumuJet_Pt20to30_miniTree_allmuons, FSR_ZmumuJet_Pt30to50_miniTree_allmuons, FSR_ZmumuJet_Pt50to80_miniTree_allmuons, FSR_ZmumuJet_Pt80to120_miniTree_allmuons, FSR_ZmumuJet_Pt120to170_miniTree_allmuons, FSR_ZmumuJet_Pt170to230_miniTree_allmuons, FSR_ZmumuJet_Pt230to300_miniTree_allmuons, FSR_ZmumuJet_Pt300toInf_miniTree_allmuons, ISR_ZmumuJet_Pt0to15_miniTree_allmuons, ISR_ZmumuJet_Pt15to20_miniTree_allmuons, ISR_ZmumuJet_Pt20to30_miniTree_allmuons, ISR_ZmumuJet_Pt30to50_miniTree_allmuons, ISR_ZmumuJet_Pt50to80_miniTree_allmuons, ISR_ZmumuJet_Pt80to120_miniTree_allmuons, ISR_ZmumuJet_Pt120to170_miniTree_allmuons, ISR_ZmumuJet_Pt170to230_miniTree_allmuons, ISR_ZmumuJet_Pt230to300_miniTree_allmuons, ISR_ZmumuJet_Pt300toInf_miniTree_allmuons, "Phi_allMuons", "Phi_allMuons", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi_{#mu}", true, false, c1);
		DrawDataMCplot(Data_miniTree_allmuons, QCD_Pt15_miniTree_allmuons, QCD_Pt30_miniTree_allmuons, QCD_Pt80_miniTree_allmuons, QCD_Pt170_miniTree_allmuons, QCD_Pt300_miniTree_allmuons, QCD_Pt470_miniTree_allmuons, PhotonJet_Pt15_miniTree_allmuons, PhotonJet_Pt30_miniTree_allmuons, PhotonJet_Pt80_miniTree_allmuons, PhotonJet_Pt170_miniTree_allmuons, PhotonJet_Pt300_miniTree_allmuons, TTbarJets_Tauola_miniTree_allmuons, WJets_7TeV_miniTree_allmuons, ZJets_7TeV_miniTree_allmuons, QCD_Mu_Pt20to30_miniTree_allmuons, QCD_Mu_Pt30to50_miniTree_allmuons, QCD_Mu_Pt50to80_miniTree_allmuons, QCD_Mu_Pt80to120_miniTree_allmuons, QCD_Mu_Pt120to170_miniTree_allmuons, QCD_Mu_Pt170toInf_miniTree_allmuons, InclusiveMu15_miniTree_allmuons, FSR_ZmumuJet_Pt0to15_miniTree_allmuons, FSR_ZmumuJet_Pt15to20_miniTree_allmuons, FSR_ZmumuJet_Pt20to30_miniTree_allmuons, FSR_ZmumuJet_Pt30to50_miniTree_allmuons, FSR_ZmumuJet_Pt50to80_miniTree_allmuons, FSR_ZmumuJet_Pt80to120_miniTree_allmuons, FSR_ZmumuJet_Pt120to170_miniTree_allmuons, FSR_ZmumuJet_Pt170to230_miniTree_allmuons, FSR_ZmumuJet_Pt230to300_miniTree_allmuons, FSR_ZmumuJet_Pt300toInf_miniTree_allmuons, ISR_ZmumuJet_Pt0to15_miniTree_allmuons, ISR_ZmumuJet_Pt15to20_miniTree_allmuons, ISR_ZmumuJet_Pt20to30_miniTree_allmuons, ISR_ZmumuJet_Pt30to50_miniTree_allmuons, ISR_ZmumuJet_Pt50to80_miniTree_allmuons, ISR_ZmumuJet_Pt80to120_miniTree_allmuons, ISR_ZmumuJet_Pt120to170_miniTree_allmuons, ISR_ZmumuJet_Pt170to230_miniTree_allmuons, ISR_ZmumuJet_Pt230to300_miniTree_allmuons, ISR_ZmumuJet_Pt300toInf_miniTree_allmuons, "Eta_allMuons", "Eta_allMuons", "(50,-3.0,3.0)", set_of_cuts[i], name[i], "#eta_{#mu}", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree_allmuons, QCD_Pt15_miniTree_allmuons, QCD_Pt30_miniTree_allmuons, QCD_Pt80_miniTree_allmuons, QCD_Pt170_miniTree_allmuons, QCD_Pt300_miniTree_allmuons, QCD_Pt470_miniTree_allmuons, PhotonJet_Pt15_miniTree_allmuons, PhotonJet_Pt30_miniTree_allmuons, PhotonJet_Pt80_miniTree_allmuons, PhotonJet_Pt170_miniTree_allmuons, PhotonJet_Pt300_miniTree_allmuons, TTbarJets_Tauola_miniTree_allmuons, WJets_7TeV_miniTree_allmuons, ZJets_7TeV_miniTree_allmuons, QCD_Mu_Pt20to30_miniTree_allmuons, QCD_Mu_Pt30to50_miniTree_allmuons, QCD_Mu_Pt50to80_miniTree_allmuons, QCD_Mu_Pt80to120_miniTree_allmuons, QCD_Mu_Pt120to170_miniTree_allmuons, QCD_Mu_Pt170toInf_miniTree_allmuons, InclusiveMu15_miniTree_allmuons, FSR_ZmumuJet_Pt0to15_miniTree_allmuons, FSR_ZmumuJet_Pt15to20_miniTree_allmuons, FSR_ZmumuJet_Pt20to30_miniTree_allmuons, FSR_ZmumuJet_Pt30to50_miniTree_allmuons, FSR_ZmumuJet_Pt50to80_miniTree_allmuons, FSR_ZmumuJet_Pt80to120_miniTree_allmuons, FSR_ZmumuJet_Pt120to170_miniTree_allmuons, FSR_ZmumuJet_Pt170to230_miniTree_allmuons, FSR_ZmumuJet_Pt230to300_miniTree_allmuons, FSR_ZmumuJet_Pt300toInf_miniTree_allmuons, ISR_ZmumuJet_Pt0to15_miniTree_allmuons, ISR_ZmumuJet_Pt15to20_miniTree_allmuons, ISR_ZmumuJet_Pt20to30_miniTree_allmuons, ISR_ZmumuJet_Pt30to50_miniTree_allmuons, ISR_ZmumuJet_Pt50to80_miniTree_allmuons, ISR_ZmumuJet_Pt80to120_miniTree_allmuons, ISR_ZmumuJet_Pt120to170_miniTree_allmuons, ISR_ZmumuJet_Pt170to230_miniTree_allmuons, ISR_ZmumuJet_Pt230to300_miniTree_allmuons, ISR_ZmumuJet_Pt300toInf_miniTree_allmuons, "Charge_allMuons", "Charge_allMuons", "(20,-2,2)", set_of_cuts[i], name[i], "Charge_{#mu}", true, false, c1);

		DrawDataMCplot(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "Pt_allPhotons", "Pt_allPhotons", "(100,0,100)", set_of_cuts[i], name[i], "p_{T_{#gamma}} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "Phi_allPhotons", "Phi_allPhotons", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi_{#gamma}", true, false, c1);
		DrawDataMCplot(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "Eta_allPhotons", "Eta_allPhotons", "(50,-3.0,3.0)", set_of_cuts[i], name[i], "#eta_{#gamma}", true, false, c1);
//FIXME		DrawDataMCplot(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "Cross_allPhotons", "Cross_allPhotons", "(50,-1.0,1.5)", set_of_cuts[i], name[i], "cross_{#gamma}", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "isEB_allPhotons", "isEB_allPhotons", "(20,-1,2)", set_of_cuts[i], name[i], "#gamma isEB", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "isEE_allPhotons", "isEE_allPhotons", "(20,-1,2)", set_of_cuts[i], name[i], "#gamma isEE", true, false, c1);
//		DrawDataMCplot_TH1I(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "isEEM_allPhotons", "isEEM_allPhotons", "(20,-1,2)", set_of_cuts[i], name[i], "#gamma isEEM", true, false, c1);
//		DrawDataMCplot_TH1I(Data_miniTree_allphotons, QCD_Pt15_miniTree_allphotons, QCD_Pt30_miniTree_allphotons, QCD_Pt80_miniTree_allphotons, QCD_Pt170_miniTree_allphotons, QCD_Pt300_miniTree_allphotons, QCD_Pt470_miniTree_allphotons, PhotonJet_Pt15_miniTree_allphotons, PhotonJet_Pt30_miniTree_allphotons, PhotonJet_Pt80_miniTree_allphotons, PhotonJet_Pt170_miniTree_allphotons, PhotonJet_Pt300_miniTree_allphotons, TTbarJets_Tauola_miniTree_allphotons, WJets_7TeV_miniTree_allphotons, ZJets_7TeV_miniTree_allphotons, QCD_Mu_Pt20to30_miniTree_allphotons, QCD_Mu_Pt30to50_miniTree_allphotons, QCD_Mu_Pt50to80_miniTree_allphotons, QCD_Mu_Pt80to120_miniTree_allphotons, QCD_Mu_Pt120to170_miniTree_allphotons, QCD_Mu_Pt170toInf_miniTree_allphotons, InclusiveMu15_miniTree_allphotons, FSR_ZmumuJet_Pt0to15_miniTree_allphotons, FSR_ZmumuJet_Pt15to20_miniTree_allphotons, FSR_ZmumuJet_Pt20to30_miniTree_allphotons, FSR_ZmumuJet_Pt30to50_miniTree_allphotons, FSR_ZmumuJet_Pt50to80_miniTree_allphotons, FSR_ZmumuJet_Pt80to120_miniTree_allphotons, FSR_ZmumuJet_Pt120to170_miniTree_allphotons, FSR_ZmumuJet_Pt170to230_miniTree_allphotons, FSR_ZmumuJet_Pt230to300_miniTree_allphotons, FSR_ZmumuJet_Pt300toInf_miniTree_allphotons, ISR_ZmumuJet_Pt0to15_miniTree_allphotons, ISR_ZmumuJet_Pt15to20_miniTree_allphotons, ISR_ZmumuJet_Pt20to30_miniTree_allphotons, ISR_ZmumuJet_Pt30to50_miniTree_allphotons, ISR_ZmumuJet_Pt50to80_miniTree_allphotons, ISR_ZmumuJet_Pt80to120_miniTree_allphotons, ISR_ZmumuJet_Pt120to170_miniTree_allphotons, ISR_ZmumuJet_Pt170to230_miniTree_allphotons, ISR_ZmumuJet_Pt230to300_miniTree_allphotons, ISR_ZmumuJet_Pt300toInf_miniTree_allphotons, "isEEP_allPhotons", "isEEP_allPhotons", "(20,-1,2)", set_of_cuts[i], name[i], "#gamma isEEP", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonL_Pt", "MuonL_Pt", "(50,0,100)", set_of_cuts[i], name[i], "p_{T} #mu_{leading} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonS_Pt", "MuonS_Pt", "(50,0,100)", set_of_cuts[i], name[i], "p_{T} #mu_{subleading} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonL_Eta", "MuonL_Eta", "(50,-3,3)", set_of_cuts[i], name[i], "#eta #mu_{leading}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonS_Eta", "MuonS_Eta", "(50,-3,3)", set_of_cuts[i], name[i], "#eta #mu_{subleading}", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonL_Phi", "MuonL_Phi", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi #mu_{leading}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonS_Phi", "MuonS_Phi", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi #mu_{subleading}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonL_Charge", "MuonL_Charge", "(20,-2,2)", set_of_cuts[i], name[i], "charge #mu_{leading}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonS_Charge", "MuonS_Charge", "(20,-2,2)", set_of_cuts[i], name[i], "charge #mu_{subleading}", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonF_Pt", "MuonF_Pt", "(50,0,100)", set_of_cuts[i], name[i], "p_{T} #mu_{far} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonN_Pt", "MuonN_Pt", "(50,0,100)", set_of_cuts[i], name[i], "p_{T} #mu_{near} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonF_Eta", "MuonF_Eta", "(50,-3,3)", set_of_cuts[i], name[i], "#eta #mu_{far}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonN_Eta", "MuonN_Eta", "(50,-3,3)", set_of_cuts[i], name[i], "#eta #mu_{near}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonF_Phi", "MuonF_Phi", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi #mu_{far}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonN_Phi", "MuonN_Phi", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi #mu_{near}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonF_Charge", "MuonF_Charge", "(20,-2,2)", set_of_cuts[i], name[i], "charge #mu_{far}", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "MuonN_Charge", "MuonN_Charge", "(20,-2,2)", set_of_cuts[i], name[i], "charge #mu_{near}", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Mmumu", "Mmumu", "(100,0,300)", set_of_cuts[i], name[i], "M_{#mu#mu} (GeV)", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Mmumugamma", "Mmumugamma", "(100,0,300)", set_of_cuts[i], name[i], "M_{#mu#mu#gamma} (GeV)", true, false, c1);
	

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRNear", "deltaRNear", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{near})", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRFar", "deltaRFar", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{far})", true, false, c1);
//		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRPlus", "deltaRPlus", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{plus})", true, false, c1);
//		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRMinus", "deltaRMinus", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{minus})", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRLeading", "deltaRLeading", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{leading})", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "deltaRSubleading", "deltaRSubleading", "(100,0,10)", set_of_cuts[i], name[i], "#Delta R(#gamma, #mu_{subleading})", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_Eta", "Photon_Eta", "(50,-3,3)", set_of_cuts[i], name[i], "#eta of photon", true, false, c1);
		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_Phi", "Photon_Phi", "(50,-3.15,3.15)", set_of_cuts[i], name[i], "#phi of photon", true, false, c1);

		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_isEB", "Photon_isEB", "(10,-1,2)", set_of_cuts[i], name[i], "photon is in barrel", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_isEE", "Photon_isEE", "(10,-1,2)", set_of_cuts[i], name[i], "photon is in endcap", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_isEEP", "Photon_isEEP", "(10,-1,2)", set_of_cuts[i], name[i], "photon is in endcap plus", true, false, c1);
		DrawDataMCplot_TH1I(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_isEEM", "Photon_isEEM", "(10,-1,2)", set_of_cuts[i], name[i], "photon is in endcap minus", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_E", "Photon_E", "(100, 0, 100)", set_of_cuts[i], name[i], "Photon Energy (GeV)", true, false, c1);

		DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Photon_Et", "Photon_Et", "(100, 0, 100)", set_of_cuts[i], name[i], "Photon Et (GeV)", true, false, c1);

		DrawDataMCplot_TH2F(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "Mmumu", "Mmumugamma", "(900,0,300,900,0,300)", set_of_cuts[i], name[i], "M_{#mu#mu} (GeV)", "M_{#mu#mu#gamma} (GeV)", "Mmumu_VS_Mmumugamma", false, false, c1);

DrawDataMCplot_TH2F(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "((91.1876**2 - Mmumu**2 ) / (Mmumugamma**2 - Mmumu**2))*Photon_E", "Photon_E", "(400,0,100,400,0,100)", set_of_cuts[i], name[i], "E_{true} = k*E_{reco} (GeV)", "E_{reco} (GeV)", "Etrue_VS_Ereco", false, false, c1, true);

*/
	DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "(91.1876**2 - Mmumu**2 ) / (Mmumugamma**2 - Mmumu**2)", "Photon_k", "(50,0.5,1.5)", set_of_cuts[i], name[i], "k = E_{true} / E_{reco}", true, false, c1, true);
	DrawDataMCplot(Data_miniTree, QCD_Pt15_miniTree, QCD_Pt30_miniTree, QCD_Pt80_miniTree, QCD_Pt170_miniTree, QCD_Pt300_miniTree, QCD_Pt470_miniTree, PhotonJet_Pt15_miniTree, PhotonJet_Pt30_miniTree, PhotonJet_Pt80_miniTree, PhotonJet_Pt170_miniTree, PhotonJet_Pt300_miniTree, TTbarJets_Tauola_miniTree, WJets_7TeV_miniTree, ZJets_7TeV_miniTree, QCD_Mu_Pt20to30_miniTree, QCD_Mu_Pt30to50_miniTree, QCD_Mu_Pt50to80_miniTree, QCD_Mu_Pt80to120_miniTree, QCD_Mu_Pt120to170_miniTree, QCD_Mu_Pt170toInf_miniTree, InclusiveMu15_miniTree, FSR_ZmumuJet_Pt0to15_miniTree, FSR_ZmumuJet_Pt15to20_miniTree, FSR_ZmumuJet_Pt20to30_miniTree, FSR_ZmumuJet_Pt30to50_miniTree, FSR_ZmumuJet_Pt50to80_miniTree, FSR_ZmumuJet_Pt80to120_miniTree, FSR_ZmumuJet_Pt120to170_miniTree, FSR_ZmumuJet_Pt170to230_miniTree, FSR_ZmumuJet_Pt230to300_miniTree, FSR_ZmumuJet_Pt300toInf_miniTree, ISR_ZmumuJet_Pt0to15_miniTree, ISR_ZmumuJet_Pt15to20_miniTree, ISR_ZmumuJet_Pt20to30_miniTree, ISR_ZmumuJet_Pt30to50_miniTree, ISR_ZmumuJet_Pt50to80_miniTree, ISR_ZmumuJet_Pt80to120_miniTree, ISR_ZmumuJet_Pt120to170_miniTree, ISR_ZmumuJet_Pt170to230_miniTree, ISR_ZmumuJet_Pt230to300_miniTree, ISR_ZmumuJet_Pt300toInf_miniTree, "(91.1876**2 - Mmumu**2 ) / (Mmumugamma**2 - Mmumu**2)", "Photon_k_extended", "(50, -1.0 , 4.0)", set_of_cuts[i], name[i], "k = E_{true} / E_{reco}", true, false, c1, true);


	}
	return 0;	
}

